Add min lint score

diff --git a/.github/workflows/static_analysis.yml b/.github/workflows/static_analysis.yml
--- a/.github/workflows/static_analysis.yml
+++ b/.github/workflows/static_analysis.yml
@@ -11,12 +11,12 @@ jobs:
 
     steps:
     - name: Check out repository code
-      uses: actions/checkout@v3
+      uses: actions/checkout@v2
 
     - name: Set up Python
-      uses: actions/setup-python@v3
+      uses: actions/setup-python@v2
       with:
-        python-version: '3.10.10' # Specify the Python version
+        python-version: '3.8' # Specify the Python version
 
     - name: Install dependencies
       run: |
@@ -26,4 +26,11 @@ jobs:
     - name: Run Pylint
       run: |
         pip install pylint
-        pylint $(git ls-files '*.py')
+        pylint_output=$(pylint $(git ls-files '*.py'))
+        echo "$pylint_output"
+        score=$(echo "$pylint_output" | grep 'Your code has been rated at' | awk '{print $7}' | sed 's/\/10//')
+        echo "Pylint score: $score"
+        if (( $(echo "$score < 8.0" | bc -l) )); then
+          echo "Pylint score is below 8.0, failing the build"
+          exit 1
+        fi
